#!/bin/bash

# Install jwt-cli first. https://github.com/mike-engel/jwt-cli
# Create "gen-token-config" file with following variables:
# ISSUER=...
# AUDIENCE=...
# SECRET=...

source gen-token-config

ID=$1
NICKNAME=$2

if [ -z "$3" ]; then
	EMAIL="$NICKNAME@cosmicchamps.com"
else
	EMAIL=$3
fi

jwt encode --alg=HS256 --exp=365d --iss=$ISSUER --aud=$AUDIENCE --secret=$SECRET "{\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier\":\"$ID\", \"nickname\":\"$NICKNAME\", \"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress\":\"$EMAIL\"}"