#!/bin/bash

#Make sure you have installed AWS Session Manager plugin https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html

read -r instance_id instance_ip <<< `aws --region eu-central-1 gamelift list-compute --fleet-id=$1 --query "ComputeList[$2].[InstanceId,IpAddress]" --output text`
read -r access_key_id secret_access_key session_token <<< `aws --region eu-central-1 gamelift get-compute-access --fleet-id $1 --compute-name $instance_id --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text`

#export AWS_ACCESS_KEY_ID=$access_key_id
#export AWS_SECRET_ACCESS_KEY=$secret_access_key
#export AWS_SESSION_TOKEN=$session_token

AWS_ACCESS_KEY_ID=$access_key_id AWS_SECRET_ACCESS_KEY=$secret_access_key AWS_SESSION_TOKEN=$session_token aws ssm start-session --target=$instance_id --region eu-central-1